### ISSUE TITLE
Share training slides for review

### ISSUE THREAD

**Issue by marialauracangiano** [precision-sustainable-ag/PlantMap3D-Management#15]
Slides should be shared by Wednesday November 15th

**Comment by mtfunder** [comment]
No real formatting or pictures yet but I think I have the general flow of the presentation covered. Some slides might multiply to cover the needed Info for a particular topic.

https://docs.google.com/presentation/d/1KmA-zlPt4on8yCpVi4VQ5vAJqa9yNLwxPoSxt75fuzc/edit#slide=id.g29be5d7daba_0_342

**Comment by mtfunder** [comment]
I also added all the PM3D pictures I have so far to this folder https://drive.google.com/drive/folders/12NySTLtSrmhQZyjvpZ02sp9pqMP-0spr?usp=drive_link

I also have a block diagram, but I want to update it a bit before adding it to the slideshow.
